name: grocery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  #--------[packages]---------
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  iconsax: ^0.0.8
  provider: ^6.1.5+1
  cloud_firestore: ^6.1.0
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  get_storage: ^2.1.1
  firebase_storage: ^13.0.4
  shimmer: ^3.0.0
  intl: ^0.20.2
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  connectivity_plus: ^7.0.0


  #---------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  #--------[assets]---------
  assets:
    - assets/logo/
    - assets/animations/
    - assets/images/


  #--------[fonts]---------
  fonts:
    - family: 'Nunito'
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800





